package SelfLearningByHerbertSchildt.Chapter10.NestedTry;

/*
Try statements can be implicitly nested via calls to methods
 */

public class MethNestTry {
    static void nesttry(int a){  // Nested try block
        try {
            /*
            If a command-line arg is used, then a divide-by-zero
            will be generated by a following code
             */
            if (a == 1) a = a / (a - a); // Division by zero
            /*
            If two command-line args are used then  generate an out-of-bounds exception
             */
            if (a == 2) {
                int[] c = {1};
                c[42] = 99; // Generate an out-of-bounds exception
            }
        }catch (ArrayIndexOutOfBoundsException e){
            System.out.println("Array index-out-of Bounds: "+e);
        }
    }
    public static void main(String[] args){
        try{
            int a=args.length;

            /*
            If no command-line-argument are present, the following statement
            will generate a divide-by-zero exception
             */
            int b=42/a;
            System.out.println("a = "+a);
            nesttry(a);
        }catch (ArithmeticException e){
            System.out.println("Divide by zero: "+e);
        }
    }
}
