package SelfLearningByHerbertSchildt.Chapter10.NestedTry;


// An example of nested try statement
public class NestTry {
    public static void main(String[] args){
        try{
            int a=args.length;
            /*
            if no command-line-arguments are present,
            the following statement will generate
            a divide-by-zero exception
             */
            int b=42/a;
            System.out.println("a = "+a);

            try {// Nested try block
                /*
                If one command-line arg is used,
                then a divide-by-zero exception will be
                generated by the following code
                 */
                if (a == 1) {
                    a=a/(a-a); // Division by zero
                }
                /*
                if two command line args are used
                then generate an out-of-bound exception
                 */
                if(a==2){
                    int [] c={1};
                    c[42]=99;// Generate out of bound exception
                }
            }catch (ArrayIndexOutOfBoundsException e){
                System.out.println("Array index out-of-bound exception: "+e);
            }
        }catch (ArithmeticException e){
            System.out.println("Divide by zero: "+e);
        }
    }
}
